#!/usr/bin/env bash
# Install nginx, set up to listen to port 80 and change default page served to
# "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
